### ISSUE TITLE
Improve GitHub Actions

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus-gui#132]
GitHub Actions can be improved by:  

1. Creating separate actions for linting and testing.  
2. Decoupling the notification process from the release action.  

The notification action should be triggered after the release process is completed, like this:  

```yaml
name: Notify Release

on:
  workflow_run:
    workflows: ["Release Software"]  ## Ensure the name matches
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
...

      - name: Notify Slack
...

      - name: Notify XYZ
...

```
